### ISSUE TITLE
Setup Staging Bucket

### ISSUE THREAD

**Issue by NoopDog** [HumanCellAtlas/dcp-preview#13]

**Comment by parthshahva** [comment]
preview.staging.data.humancellatlas.org.s3-website-us-east-1.amazonaws.com, setting up the prerequisite certificate now for preview.staging.data.humancellatlas.org. Ideally, we will use terraform and travis to automate deployment of a staging branch to staging before any manual pushes to master. This, in my opinion, will be a simple + good pattern for deployment of similar pages in the HCA.

**Comment by parthshahva** [comment]
certificate granted: https://preview.staging.data.humancellatlas.org setup. Closing issue.
